site_name: Xamarin Android Guide - Peruzal
repo_url: https://github.com/Peruzal/xamarin-android-guide
theme:
  name: material
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'orange'
    accent: 'orange'

markdown_extensions:
  - admonition
  - codehilite: 
      linenums: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.arithmatex

google_analytics:
  - 'UA-40772582-8'
  - 'auto'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


copyright: 'Copyright &copy; 2019 - <a href="https://www.peruzal.com">Peruzal</a>'

nav:
  - Introduction: index.md
  - Hello Xamarin.Android: hello-xamarin-android.md
  - Android Components: android-components.md
  - Android Views: android-views.md
  - Common Views: common-views.md
  - Menus: menus.md
  - App Resources: app-resources.md
  - Layouts: layouts.md
  - Activities: activities.md
  - RecyclerView: recyclerview.md
  - Navigation: navigation.md
  - Fragments: fragments.md
  - Dialogs and Pickers: dialogs.md
  - Common Intents: common-intents.md
  - Networking: networking.md
  - Permissions: permissions.md
  - Persistence: persistence.md
  - Styles and Themes: styles-and-themes.md
  - Animation: animations.md
  - Notifications: notifications.md
  - Broadcast Receivers: broadcast-receivers.md
  - Services: services.md
  - Scheduling Alarms: scheduling-alarms.md
  - Maps and Location: maps-and-location.md
  - Testing: testing.md
  - Third Party Libraries: third-party-libraries.md
  - Deployment: deployment.md